name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
       echo ${{secrets.DB_URL}}
       echo 'export DB_PASSWORD="${{secrets.DB_URL}}"' >> ~/.bashrc
       echo ${{secrets.DB_URL}}
       echo $DB_PASSWORD
      
